# Generated by Django 4.2.2 on 2023-07-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('lastname', models.CharField(max_length=75)),
                ('age', models.SmallIntegerField()),
                ('profession', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
