# Generated by Django 4.2.2 on 2023-07-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catdog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalimage',
            name='species',
            field=models.CharField(choices=[('cat', 'Kitten'), ('dog', 'Dog')], default='cat', max_length=5),
        ),
    ]
